### ISSUE TITLE
Blank front page

### ISSUE THREAD

**Issue by flicstar** [thegooddocsproject/thegooddocsproject.github.io#1]
The website displayed fine when it was a simple github one-pager. I installed ruby so that I could use jekyll and apply the Slate theme. 
Now the URL displays blank - I think I'm missing a file or something! Suspect it's very simple.

**Comment by flicstar** [comment]
Jo tweaked some things and now it displays, Yay.

**Comment by archaeogeek** [comment]
Suspect we've still got some work to do here- it's not working for me at all :-(
