### ISSUE TITLE
Get logo design and apply it to GitHub, Twitter, Slack, Website

### ISSUE THREAD

**Issue by flicstar** [thegooddocsproject/thegooddocsproject.github.io#11]
Get logo design and apply it to GitHub, Twitter, Slack, Website

**Comment by jaredmorgs** [comment]
When you say "logo" you mean the black on white TGD in a page icon. In that case:

- [x] GitHub
- [x] Twitter
- [x] Slack
- [ ] Website

**Comment by jaredmorgs** [comment]
The only thing we need to get the logo on is our Website. What needs to happen to make that a possibility?

**Comment by flicstar** [comment]
Yeah, the logo we have at the moment is craptacular but I suppose it _is_ technically a logo. 
This issue was about applying the new logo to all those places.
Erin said today (6/11) that she is working on a new design and should have a draft by the Sydney conference.

**Comment by jaredmorgs** [comment]
Let's get the current logo up on our website and if @emckean can get another one done up before next Wednesday we'll consider that.

**Comment by flicstar** [comment]
I tried my best. Got *no idea* how to add the logo to the website. I _think_ we need to add the stylesheet as explained here https://github.com/pages-themes/slate and then make a div or something to put the image in and put that div next to the page title? 
But where? in _layouts?  in the .yaml? IFIIK. 
Here is the png if anyone wants to have a go.
![TGD_logo_invert](https://user-images.githubusercontent.com/10190723/68541077-320cfb00-03ef-11ea-8614-9cd4b9307f71.png)

**Comment by totewar** [comment]
@emckean shared some ideas and a list of pencil typefaces with me. I shared this with some artists and they will be getting back to me this weekend. On the other hand, I am also in touch with people in design and they have some cool ideas. I should be able to share some concepts and/or designs with you and others early next week.

**Comment by totewar** [comment]
Btw, would love to know if we want to use **The Good Docs**, **The Good Docs Project**, or **Good Docs Project**?

**Comment by flicstar** [comment]
I think we had a conversation about this fairly early on (I would have
go back through the mailing lists to refresh my memory) but I *think*
we said the full "The Good Docs Project" until we become more
well-known, and then we can probably drop the "Project" and just be
"The Good Docs".

Can anyone else shed any light?

**Comment by totewar** [comment]
Thanks, @flicstar 

Btw, I have some news.

There's an interesting discussion that one should have two sets of logos
1. a square logo that is identifiable and can be used on social media and promotional materials
2. a full logo that has the square logo and then letters before/after/ on either side and this can be used on the website and printed material (and make it easier to find the website).

Regarding number 1, one of the top ideas in the discussion is 
- having a document that has a fold at the bottom right and is a little curved so it looks like a D
- a nimbus on top of this doc which specifies that it's like an angel or is good

This is mostly voluntary so I should be able to share a draft sketch tomorrow or the day after and then based on feedback from you all, I could consider making the actual vector graphic.

If we ever decide to create an animation, the nimbus could form the O of DOCS and the document D, which would be in line with any phrase we go with.

Number 2 can simply form the words "The Good Docs Project" or "The Good Docs" with D being the square logo and the other letters being in a pencil font.

There are a couple of other discussions and if anything interesting comes up, I'll share them as sketches too.

**Comment by flicstar** [comment]
You mention a lot of discussions happening @totewar. Whereabouts are they happening? Who are they with? I'd hate to be missing out - but the ideas sound good.

**Comment by totewar** [comment]
They are face-to-face discussions with artists in Leura (Australia) and design people in my company (Australia) and other designers I know (India). Most artists I know are not active digitally and designers are not keen to join the mailing list as they see this as a one-time activity.

I look forward to feedback from you all once I share some sketches.

**Comment by rcaballeromx** [comment]
This issue should be addressed as part of the Hugo migration to ensure proper implementation. We will vote to confirm that the mascot will be our logo.

**Comment by flicstar** [comment]
I'm working on this. Have updated Slack and GitHub with the doctopus. Still working on Twitter.

**Comment by flicstar** [comment]
Twitter is now updated. I am going to close this issue and let the Hugo website migration implement the Doctopus as part of their work.
