### ISSUE TITLE
Merge "governance", "structure", "planning" repos into the "website" repo

### ISSUE THREAD

**Issue by flicstar** [thegooddocsproject/thegooddocsproject.github.io#14]
Or should they go into the templates repo. Not sure. This was a comment from Cameron as a to-do. I think we just want all our meta into in the one place.

**Comment by camerons** [comment]
Our governance type informantion is difficult to find from our website and as such, should be moved into our website repository. So I suggest our website be restructured to something like:

- "Home" (Merge "About" into here)
- "Licenses" (As before)
- "Download" (New. Points to our templates github and snapshots, https://github.com/thegooddocsproject/templates/releases/tag/v0.1)
+ "Community" (New jump page)
  - "Contribute" (As before, moved down one level)
  - "Code of Conduct" (Moved from https://github.com/thegooddocsproject/governance/blob/master/CodeOfConduct.md)
  - "Contact Us" (As before, moved down one level)
    - "Meeting minutes" (Moved from https://github.com/thegooddocsproject/governance/wiki/Weekly-Meetings)
  - "Roles" (Extended from https://github.com/thegooddocsproject/governance/blob/master/ProjectSteeringCommittee.md)
  - "Decisions" (Extracted from https://github.com/thegooddocsproject/governance/blob/master/ProjectSteeringCommittee.md)
  - "Decision Log 2020" (Extracted from https://github.com/thegooddocsproject/governance/wiki/Decision-Log-2020) 
  - "Decision Log 2019" (Extracted from https://github.com/thegooddocsproject/governance/wiki/Decision-Log-2019) 
  - "Press" (Moved from https://github.com/thegooddocsproject/governance/wiki/Announcements)

**Comment by viraji** [comment]
I'm going to be working on this today, just FYI.

**Comment by camerons** [comment]
Website is live with the changes. So we can close this.
