### ISSUE TITLE
QA our website 

### ISSUE THREAD

**Issue by flicstar** [thegooddocsproject/thegooddocsproject.github.io#15]
https://thegooddocsproject.dev/
Make sure it looks fab and all the links work and it says want we want it to.

**Comment by totewar** [comment]
I've started on this front. More details here:
https://docs.google.com/document/d/1gzoSWvZEgNU96WwgmeLiqeD5FbGMBgezpkXWhKFGdkw/edit?usp=sharing

I'll add a comment here once I'm done with an initial pass.

**Comment by totewar** [comment]
I'll try to send a PR to fix the links and some changes in text tonight.

**Comment by totewar** [comment]
So I made a few changes and tried to push to GitHub but it seems that I lack permissions. I wasn't able to create a branch and keep getting errors. Am I missing something?

**Comment by flicstar** [comment]
What do the errors say? We do still need to remove the DCO thing which has caused folk some problems before. But you should be able to fork, branch then do a PR, I would have thought. Let me check your permissions.

**Comment by totewar** [comment]
It seems to be working now so we're back in business. Yaay!

**Comment by totewar** [comment]
I am keeping this issue open in case someone wishes to pick up on the content - I have fixed the broken links

**Comment by camerons** [comment]
Thanks @totewar for the review, I'm closed this out as a specific issue. We can raise a new ticket if needed during future reviews.
