### ISSUE TITLE
Write a good Readme for website repo

### ISSUE THREAD

**Issue by flicstar** [thegooddocsproject/thegooddocsproject.github.io#16]

**Comment by jaredmorgs** [comment]
@flicstar what exactly is required here?

I see that in https://github.com/thegooddocsproject/thegooddocsproject.github.io/blob/master/index.md there is some content already about what this project is about.

Would it be better to promote this content (even copy-pasta) into a README.md at the same level as index.md?

**Comment by jaredmorgs** [comment]
![image](https://user-images.githubusercontent.com/952793/68083361-8c4c1000-fe73-11e9-8779-fa06bd705922.png)

What we should do is update our GitHub Repo organisation statement to put a link to our website and an overarching project description. 

Steal it from the index.md file perhaps?

**Comment by jaredmorgs** [comment]
The other option is that we cherry-pick content out of the hanging PR in this project and make that content into the repository readme.

**Comment by flicstar** [comment]
Yeah, lets do one or all of those things 👍 
I only created the issue because Jo said "we need good readmes". So I was just trying to be complete.

**Comment by camerons** [comment]
I'm closing out this issue for 0.1 release. We do have README files in our templates now. For our future releases we can create a new issue if required to improve the existing READMEs. (This is likely to happen based on feedback from reviews in the WriteTheDocs community.
