### ISSUE TITLE
Update the repo description to link to our website (at a minimum)

### ISSUE THREAD

**Issue by jaredmorgs** [thegooddocsproject/thegooddocsproject.github.io#17]
![image](https://user-images.githubusercontent.com/952793/68083709-a7208380-fe77-11e9-8a34-64df67ff13e4.png)

We need to fill in a repo description for each of these repositories otherwise it looks not so great.

**Comment by flicstar** [comment]
Okay, I added a one-liner description for each of the repos. Wasn't sure what to write for the "templates" repo. Feel free to change.

**Comment by flicstar** [comment]
Closing issue. See comment above. Should've put that comment here. Learning!
