### ISSUE TITLE
Proposal: Track announcements

### ISSUE THREAD

**Issue by archaeogeek** [thegooddocsproject/thegooddocsproject.github.io#19]
* Confirm suggesting with committee (DONE)
* Track prior announcements in a wiki (DONE)
* Set up announcement email list

**Comment by archaeogeek** [comment]
@camerons @flicstar @emckean https://thegooddocsproject.groups.io/g/announce now created. Settings should be reviewed- currently set so that moderators only can post. Otherwise same settings as for main group. Reply here when you've had a chance to review

**Comment by camerons** [comment]
I've forwarded prior announcements to the announce email list (so they are archived).
I've now added all people from our general list to the announce list.
So I now think that we have the announce list complete and this issue can be closed.
