### ISSUE TITLE
Proto-Personas

### ISSUE THREAD

**Issue by totewar** [thegooddocsproject/thegooddocsproject.github.io#20]
Hi All,

During the WTD 2019 Conference, I created a new document to capture the different proto-personas that will use our templates and other material we create. The idea is to identify some proto-personas and then, for each, define the
- bio
- personality
- tasks and behavior
- frustrations/pain points
- motivations
- goals

and highlight the _facts we know_ for each.

There is a working Google Doc [here](https://docs.google.com/document/d/1gA8BAscpRdrSf4ptyUxfYHhpfe_yA78zhVPPJl5WhxU/edit).

I am wondering where these could reside in the GitHub repo. What are your thoughts on this?

**Comment by camerons** [comment]
This task is not being actively worked anymore, and probably will become part of one of the template initiatives. I'll close this task with no action.
