### ISSUE TITLE
Add a "Press" or "Mentions" page

### ISSUE THREAD

**Issue by emckean** [thegooddocsproject/thegooddocsproject.github.io#24]
we should have a page to link to blog posts, etc. about the project

**Comment by camerons** [comment]
This wiki page provides links: https://github.com/thegooddocsproject/governance/wiki/Announcements
We can close this issue once the governance pages are findable from the master pages.

**Comment by emckean** [comment]
Thanks Cameron! I was thinking that we needed a place to link *external* press about the project, I'm not sure that folks will look on the Announcements page to see other people's blog posts. :)

**Comment by camerons** [comment]
Cool, lets change https://github.com/thegooddocsproject/governance/wiki/Announcements to Press, as the content of Announcements is what you have described as Press.

**Comment by camerons** [comment]
We now have https://thegooddocsproject.dev/press/ so this issue has been addressed and can be closed.
