### ISSUE TITLE
staw-man to straw-man

### ISSUE THREAD

**Issue by marikavertzonis** [thegooddocsproject/thegooddocsproject.github.io#34]
Feel terrible I've been watching from the sidelines since WTD2019 and now I come in spot a typo (but it was in the second line I read)

https://github.com/thegooddocsproject/thegooddocsproject.github.io/blob/fb55229772c676bc18d786291beeee4fd61c19ab/index.md#L5

**Comment by emckean** [comment]
fixed with [PR#36](https://github.com/thegooddocsproject/thegooddocsproject.github.io/pull/36). Thank you! :)
