### ISSUE TITLE
Use Netlify for branch previews

### ISSUE THREAD

**Issue by ddbeck** [thegooddocsproject/thegooddocsproject.github.io#37]
## User story

As a reviewer, I want to be able to see, in addition to a diff, what a PR actually does, by building the site from the `HEAD` of a PR branch. I don't want to check out the pull request branch or maintain an up-to-date Jekyll install locally to do this.

## Background

At last week's meeting, I was asked to explore our options for generating shareable previews for changes to the project site.

## Proposal

Use [Netlify's deploy previews](https://docs.netlify.com/site-deploys/overview/#branch-deploy-controls) to generate preview builds of the project site. It's free, quick to set up (≤15 minutes, in my experience), and integrates into GitHub neatly. We can try it without impacting the existing site deployment.

## Steps to implement

In general terms, here's what would need to be done:

- [ ] [Sign up](https://app.netlify.com/signup) for a Netlify account for the thegooddocsproject. The person who does this should be a member of the thegooddocsproject org and have access to this repository's settings.
- [ ] Store securely the email and password for the account with the project's other credentials (in 1Password?).
- [ ] In Netlify, click the **Create a new site** button to start the setup process. Choose GitHub and the the thegooddocsproject/thegooddocsproject.github.io repo. This requires granting Netlify access to thegooddocsproject's repositories (or the one repo alone). Build settings and other details should automatically populate based on the Jekyll config.

After clicking **Deploy site**, Netlify should begin generating preview links in PRs, but you may have to push a new commit to the PR branch to trigger an initial build.

## Follow up tasks

If we're happy with branch previews, we may want to consider using Netlify for deployment (so there's a single build environment). We should consider this as a follow-up task.

If we're unhappy with branch previews, we should remove the project from Netlify and disconnect Netlify's access to the repository in the settings.

**Comment by emckean** [comment]
This sounds like a great plan to me :) I can help with the 1Password setup.

**Comment by camerons** [comment]
Thanks Daniel, from your description, this sounds like a great idea.
(My original question was how would I set up a local jekyll build, which I'm still interested to know, but this solution sounds more useful.)

**Comment by emckean** [comment]
Jekyll is actually fairly straightforward to run locally -- I think I have two or three Jekyll sites running (including the semicolonappreciationsociety.com site  😂 ). 

The only tricky part can be making sure your Ruby environment is up-to-date. (The Jekyll documentation is here: https://jekyllrb.com/docs/installation/)

**Comment by ScriptAutomate** [comment]
For additional awareness on getting up-and-running, we do need those details documented somewhere, as referenced here: #33

**Comment by mgan59** [comment]
Few thoughts here
1. I don't know if you need 1Password.  Believe netlify supports admin roles/permissions for multi-github-users.  Might just be adding complexity with 1Password.  The one thing being netlify may charge for user-licenses, that is how they used to do it, may of changed their pricing.
2. Not sure if the repository is going to just build right out of the box.  In resolving pr #35 I fixed part of the build, but still a few kinks to work out.

**Comment by ddbeck** [comment]
>  Believe netlify supports admin roles/permissions for multi-github-users

Yep, you're right Morgan. Netlify offers a free multi-user plan for open source projects. So I guess we can skip the whole credentials thing and sign up here: https://www.netlify.com/legal/open-source-policy/ (We will need to add a link to Netlify on the site as well, though.)

**Comment by bwklein** [comment]
This works in the new website which is hosted on Netlify and has PR and branch previews enabled. See the netlify.toml file in the project root for build command details.
