### ISSUE TITLE
Change our tagline

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/thegooddocsproject.github.io#38]
I've proposed changing our tagline from:
* “Best practice templates and writing instructions for documenting open source software.”
to
* “Best practices for documenting software.”

Support provided by Jared, Lana, Viraji, and no votes against. https://thegooddocsproject.groups.io/g/main/topic/should_we_update_our_tagline/76059455?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76059455

Source doc: https://thegooddocsproject.dev home page.

**Comment by flicstar** [comment]
@camerons Can we close this one off now, since the PR was closed: 

> On email list we failed to reach consensus over the reworded tagline, so I'm going to close this with no action.

**Comment by camerons** [comment]
Ah yes, I thought I did close this, closing now.
