### ISSUE TITLE
CodeOfConduct.md moved to website directory

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/thegooddocsproject.github.io#41]
Our Code of Conduct has moved to our website directory (great), however we are still linking to the old location: https://github.com/thegooddocsproject/governance/blob/master/CodeOfConduct.md

These files should be updated.

While you are doing these changes, we align our filename to align with our style guide, and use kebab case for the file, code-of-conduct.md, as per https://developers.google.com/style/filenames

$ grep Conduct *
CodeOfConduct.md:Code of Conduct for TheGoodDocsProject
CodeOfConduct.md:*This Code-Of-Conduct is based on the [OSGeo Code-Of-Conduct](https://www.osgeo.org/code_of_conduct/) which was based on others.*
community.md:*   [Code of Conduct](https://github.com/thegooddocsproject/governance/blob/master/CodeOfConduct.md)
contact.md:We are nice to each other, in line with our [Code of Conduct](https://github.com/thegooddocsproject/governance/blob/master/CodeOfConduct.md).

I'm about to add these files too:

$ grep Conduct *
prioritization.md:*   We expect our sponsors to behave ethically and uphold business practices which align with our [Code of Conduct](https://github.com/thegooddocsproject/governance/blob/master/CodeOfConduct.md).
roles.md:*   Community members are expected to be respectful to each other, in line with our [Code of Conduct](https://github.com/thegooddocsproject/governance/blob/master/CodeOfConduct.md).

**Comment by ghost** [comment]
I'd like to work on this issue. I also found that several other links in the docs are broken. For example, the [**reach out**](https://github.com/thegooddocsproject/thegooddocsproject.github.io/blob/master/contact) link on the [Contribute](https://github.com/thegooddocsproject/thegooddocsproject.github.io/blob/master/contribute.md) page is incorrect. I'd like to fix this issue as well.

**Comment by camerons** [comment]
Hi @s-karol thanks for the offer to help.

A few of our team have move our website from this current repository at https://github.com/thegooddocsproject/thegooddocsproject.github.io to https://github.com/thegooddocsproject/website-hugo. As such https://github.com/thegooddocsproject/thegooddocsproject.github.io is effectively deprecated. (We should show actually deprecate this.)

So I suggest that you move across to checking for issues in https://github.com/thegooddocsproject/website-hugo which is published at https://thegooddocsproject.dev/ 

I'd also encourage you to come say hello to the rest of the team on our slack #welcome channel, https://thegooddocsproject.dev/community/ . In a few sentences let us know who you are and how you'd like to be involved.

Hope to talk soon. Cameron

**Comment by camerons** [comment]
I see that the CoC has been moved to our new directory, so this issue can be closed. https://thegooddocsproject.dev/code-of-conduct/
