### ISSUE TITLE
Agree on voting scale, currently: +1,+0,0,-0,-1

### ISSUE THREAD

**Issue by camerons** [thegooddocsproject/thegooddocsproject.github.io#46]
This task is to coordinate agreement in our community the the scale we use for voting in doc: decisions.md , then to update the decisions.md with community decision.

Current scale:

   +1 : For
    +0: Mildly for, but mostly indifferent	*   +0: Mildly for, but mostly indifferent
    0: Indifferent	*   0: Indifferent
    -0: Mildly against, but mostly indifferent	*   -0: Mildly against, but mostly indifferent
    -1 : Strongly against. This is expected to be accompanied by a reason.	*   -1 : Strongly against. This is expected to be accompanied by a reason.

@Loquacity
I feel like this is an odd scale to use, because +/-0 is relatively obtuse. Perhaps +2/+1/0/-1/-2 is more intuitive?

 @adohertyTS
I agree with @Loquacity on this point. Otherwise this scale is fine.

 @flicstar
flicstar 3 days ago Member
I agree with @Loquacity on this point too.

 @archaeogeek
The scale as proposed is standard within the open source community (and makes it very easy to tally up the results) so I'd prefer it stays as it is.

 @adohertyTS
If the original scale is standard in open source then I suppose we ought to go with that. I withdraw my objection.

 @Loquacity
I have never seen this scale used before, honestly. How do you tally up results effectively if you use 0 to mean three different things?

 @mgan59
agree with @Loquacity -- never seen the +0, 0, -0 reading further I see how the results come down to +1 / -1 ... so do the 0s not get counted or used in a decision?

@camerons 
This scale was inherited from the Open Source Geospatial Foundation, by all the projects and committees that I'm aware of. I'm pretty sure it was in turn inherited from Apache communities. I'm in favor of following community conventions where possible. If we can find a widely used alternative best practice, I'm happy to follow.
See: https://www.apache.org/foundation/voting.html

**Comment by camerons** [comment]
This task should also introduce more clarity around simple decisions. I'd suggest simple decisions should be based on rough consensus. See https://en.wikipedia.org/wiki/Rough_consensus and https://tools.ietf.org/html/rfc7282.
I'd suggest this should be defined as mostly positive votes from those present, and no -1 votes.
I see this being an extra sentence in the "Simple Decisions" section.

**Comment by Loquacity** [comment]
I think the main takeaway here is that using the phrase "standard in open source" is an oxymoron :wink: My main issue is that when you have three options out of five that all evaluate out to the same number (zero), you will end up losing nuance in the vote. Additionally, `+1` is used colloquially to say "yes, I agree with this". I notice that when votes are taken on the ML, people respond with `+1` not `+0` to mean they agree. So, in practice, I see us using a different scale to what is proposed here, regardless of what you or I have seen previously in other open source communities.

And with all that said, I'm out of this discussion. While I think that using a scale that includes three different values for 0 is slightly absurd, I'm not going to continue arguing about it.

**Comment by camerons** [comment]
I'm going to close this issue with no action, as we don't currently have mixed opinions, and no volunteers at the moment stepping up to drive this conversation forward.

As such, we'll stick with the voting system that we have, until someone is prepared to drive this forward.
